lista_palavras= [
    'jornalista', 'obelisco', 'igreja', 'van', 'escola', 'passageiro', 'sobrinha', 'general', 'shopping', 'navio', 
    'fonte', 'policial', 'esportista', 'tia', 'autor', 'sinagoga', 'esquecimento', 'pirâmide', 'cozinha', 'galáxia', 
    'quadro', 'tolice', 'floresta', 'skate', 'presidente', 'neve', 'conhecimento', 'espelho', 'pedestre', 'neto', 
    'sala', 'patins', 'cor', 'armário', 'iate', 'passado', 'fraqueza', 'verdade', 'tapete', 'cachorro', 'cliente', 
    'supervisor', 'madrinha', 'marrom', 'medo', 'senador', 'universidade', 'jogador', 'cunhado', 'vagão', 'gerente', 
    'farmácia', 'espaço', 'rosa', 'aeroporto', 'banheiro', 'psiquiatra', 'carroça', 'mesa', 'fisioterapeuta', 'montanha', 
    'força', 'escritor', 'enfermeiro', 'fornecedor', 'colega', 'estrada', 'militar', 'bicicleta', 'vermelho', 'magia', 
    'luz', 'jardim', 'riqueza', 'caminhão', 'sucesso', 'treinador', 'campo', 'táxi', 'subordinado', 'ódio', 'vida', 
    'futuro', 'charrete', 'céu', 'cinema', 'avó', 'atleta', 'músico', 'telhado', 'vento', 'plataforma', 'injustiça', 
    'memória', 'teto', 'café', 'mãe', 'deserto', 'caneta', 'uber', 'ciclista', 'crítico', 'deputado', 'filha', 'ferrovia', 
    'porto', 'delegado', 'sorveteria', 'avenida', 'mochila', 'destino', 'padaria', 'roteirista', 'feiura', 'terra', 'escada', 
    'biblioteca', 'pobreza', 'cortina', 'poeta', 'realidade', 'advogado', 'primo', 'estrela', 'juiz', 'estátua', 'ônibus', 
    'terminal', 'pai', 'afilhado', 'sorte', 'água', 'fantasia', 'prisão', 'covardia', 'lanchonete', 'túnel', 'quarto', 
    'redator', 'psicólogo', 'governador', 'fogo', 'planeta', 'repórter', 'universo', 'frio', 'beleza', 'desespero', 'produtor', 
    'justiça', 'paz', 'tempo', 'estação', 'monumento', 'palácio', 'caminho', 'diretor', 'supermercado', 'praia', 'templo', 
    'branco', 'caos', 'parede', 'carro', 'amor', 'vereador', 'admirador', 'desejo', 'cinza', 'secretário', 'tristeza', 'árbitro', 
    'bombeiro', 'torre', 'escuridão', 'saudade', 'roxo', 'estante', 'trem', 'porta', 'mar', 'barulho', 'museu', 'tio', 'sol', 
    'coordenador', 'gato', 'metrô', 'corredor', 'azar', 'fracasso', 'afilhada', 'skatista', 'sofá', 'prefeito', 'boutique', 'editor', 
    'filho', 'escultura', 'parque', 'ponte', 'chuva', 'felicidade', 'liberdade', 'loja', 'parceiro', 'prima', 'arranjador', 'compositor', 
    'chefe', 'brilho', 'vizinho', 'cantor', 'ator', 'computador', 'acaso', 'lua', 'sabedoria', 'atriz', 'esperança', 'soldado', 'dramaturgo', 
    'procurador', 'celular', 'romancista', 'moto', 'funcionário', 'ar', 'restaurante', 'teatro', 'fortaleza', 'enteado', 'vontade', 'médico', 
    'mesquita', 'luminária', 'cunhada', 'lancha', 'rodovia', 'rua', 'catedral', 'motorista', 'fã', 'hospital', 'harmonia', 'confeitaria', 
    'oficial', 'livro', 'poltrona', 'ordem', 'mercado', 'cantora', 'cama', 'verde', 'amizade', 'castelo', 'colaborador', 'silêncio', 'cidade', 
    'barco', 'amigo', 'ilha', 'janela', 'sonho', 'bar', 'instrumentista', 'chão', 'casa', 'viaduto', 'clínica', 'guerra', 'coragem', 'presente', 
    'irmão', 'poder', 'mosteiro', 'motociclista', 'oceano', 'dor', 'parente', 'pizzaria', 'submarino', 'cadeira', 'torcedor', 'preto', 'irmã', 
    'calor', 'morte', 'arquiteto', 'neta', 'concorrente', 'laranja', 'galeria', 'helicóptero', 'dentista', 'azul', 'promotor', 'alegria', 'ignorância', 
    'amarelo', 'praça', 'ministro', 'sobrinho', 'avião', 'engenheiro', 'mentira', 'padrinho', 'rio', 'avô', 'inimizade'
]
